version: '3'

services: 
  
  spring-docker-service:
    build:
      context: ./app-server/Docker
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    
  angular-docker-service:
    build: 
      context: ./app-ui
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
   
