version: '3'

services: 
  
  spring-docker-service:
   
    build:
      context: ./app-server/Docker
      dockerfile: Dockerfile
    expose:
      - "8080"
    
  angular-docker-service:
 
    build:
      context: ./app-ui
      dockerfile: Dockerfile
    expose:
      - "4200"